In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [6]:
df = pd.read_csv("penguins.csv")

In [7]:
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    MALE  
1       3800.0  FEMALE  
2       3250.0  FEMALE  
3          NaN     NaN  
4       3450.0  FEMALE

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [10]:
df.shape

(344, 7)

In [16]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [17]:
# filling up the missing column with median
from sklearn.impute import SimpleImputer
#setting strategy to 'Most frequent' to impute by the mean
imputer = SimpleImputer(strategy='most_frequent') #strategy can be man or median
df.iloc[:,:]=imputer.fit_transform(df)

In [18]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [22]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df["sex"]=lb.fit_transform(df["sex"])
df["sex"][:5]

0    1
1    0
2    0
3    1
4    0
Name: sex, dtype: int64

In [23]:
df.head(20)

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0   Adelie  Torgersen            39.1           18.7              181.0   
1   Adelie  Torgersen            39.5           17.4              186.0   
2   Adelie  Torgersen            40.3           18.0              195.0   
3   Adelie  Torgersen            41.1           17.0              190.0   
4   Adelie  Torgersen            36.7           19.3              193.0   
5   Adelie  Torgersen            39.3           20.6              190.0   
6   Adelie  Torgersen            38.9           17.8              181.0   
7   Adelie  Torgersen            39.2           19.6              195.0   
8   Adelie  Torgersen            34.1           18.1              193.0   
9   Adelie  Torgersen            42.0           20.2              190.0   
10  Adelie  Torgersen            37.8           17.1              186.0   
11  Adelie  Torgersen            37.8           17.3              180.0   
12  Adelie  Torgersen            41.1           17.6              182.0   
13  Adelie  Torgersen            38.6           21.2              191.0   
14  Adelie  Torgersen            34.6           21.1              198.0   
15  Adelie  Torgersen            36.6           17.8              185.0   
16  Adelie  Torgersen            38.7           19.0              195.0   
17  Adelie  Torgersen            42.5           20.7              197.0   
18  Adelie  Torgersen            34.4           18.4              184.0   
19  Adelie  Torgersen            46.0           21.5              194.0   

    body_mass_g  sex  
0        3750.0    1  
1        3800.0    0  
2        3250.0    0  
3        3800.0    1  
4        3450.0    0  
5        3650.0    1  
6        3625.0    0  
7        4675.0    1  
8        3475.0    1  
9        4250.0    1  
10       3300.0    1  
11       3700.0    1  
12       3200.0    0  
13       3800.0    1  
14       4400.0    1  
15       3700.0    0  
16       3450.0    0  
17       4500.0    1  
18       3325.0    0  
19       4200.0    1

In [24]:
df['species'].value_counts()

Adelie       152
Gentoo       124
Chinstrap     68
Name: species, dtype: int64

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen            41.1           17.0              190.0   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g  sex  
0       3750.0    1  
1       3800.0    0  
2       3250.0    0  
3       3800.0    1  
4       3450.0    0

In [26]:
from sklearn.preprocessing import LabelEncoder
for col in df.columns:
    le=LabelEncoder()
    df[col]=le.fit_transform(df[col])

In [27]:
df.head()

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0        0       2              42             56                  6   
1        0       2              45             43                 11   
2        0       2              51             49                 20   
3        0       2              58             39                 15   
4        0       2              22             62                 18   

   body_mass_g  sex  
0           31    1  
1           33    0  
2           12    0  
3           33    1  
4           19    0

In [35]:
x=df.drop(columns=['species'], axis=1)
y=df['species']

In [36]:
df.head()

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0        0       2              42             56                  6   
1        0       2              45             43                 11   
2        0       2              51             49                 20   
3        0       2              58             39                 15   
4        0       2              22             62                 18   

   body_mass_g  sex  
0           31    1  
1           33    0  
2           12    0  
3           33    1  
4           19    0

In [37]:
x

island  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0         2              42             56                  6           31   
1         2              45             43                 11           33   
2         2              51             49                 20           12   
3         2              58             39                 15           33   
4         2              22             62                 18           19   
..      ...             ...            ...                ...          ...   
339       0              58             39                 15           33   
340       0             105             12                 39           66   
341       0             136             26                 46           87   
342       0              89             17                 36           76   
343       0             131             30                 37           80   

     sex  
0      1  
1      0  
2      0  
3      1  
4      0  
..   ...  
339    1  
340    0  
341    1  
342    0  
343    1  

[344 rows x 6 columns]

In [38]:
y

0      0
1      0
2      0
3      0
4      0
      ..
339    2
340    2
341    2
342    2
343    2
Name: species, Length: 344, dtype: int64

In [40]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.3, random_state=0)

In [41]:
print("x_train", x_train.shape)
print("x_test", x_test.shape)
print("y_train", y_train.shape)
print("y_test", y_test.shape)

x_train (240, 6)
x_test (104, 6)
y_train (240,)
y_test (104,)


In [42]:
#train Random Forest Classifier on training set

from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=7, criterion='gini', random_state=0)
classifier.fit(x_train,y_train)

RandomForestClassifier(n_estimators=7, random_state=0)

In [43]:
y_pred=classifier.predict(x_test)
y_pred

array([0, 0, 0, 2, 0, 2, 0, 1, 2, 0, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0,
       2, 0, 2, 2, 2, 0, 0, 0, 2, 1, 0, 0, 0, 2, 2, 1, 0, 0, 0, 0, 0, 2,
       2, 0, 2, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 2, 1, 2, 1, 1, 0, 2, 2, 2,
       0, 2, 2, 0, 2, 2, 0, 1, 2, 0, 0, 2, 1, 1, 0, 1, 0, 0, 0, 2, 0, 2,
       0, 0, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 0, 2])

In [44]:
#confusion Matrix

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, accuracy_score

In [45]:
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[51  0  0]
 [ 0 14  2]
 [ 1  0 36]]


In [46]:
accuracy_score(y_test, y_pred)

0.9711538461538461

In [47]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.88      0.93        16
           2       0.95      0.97      0.96        37

    accuracy                           0.97       104
   macro avg       0.98      0.95      0.96       104
weighted avg       0.97      0.97      0.97       104



In [48]:
#let's try with different number of tree and gini as criterie
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [49]:
accuracy_score(y_test,y_pred)

0.9711538461538461